<?php if (session_id() == '' || !isset($_SESSION)) {
    session_start();
}
//Adding config for EMAIL
include '../../../source/setup_email.php';
$from_name = setupEmail::FROM_NAME;
$from_add = setupEmail::PAYROLL_EMAIL;
$to_lsuk = setupEmail::LSUK_GMAIL;
if (isset($_SESSION['web_UserName']) && !empty($_SESSION['web_UserName'])) {
    $_SESSION['UserName'] = $_SESSION['web_UserName'];
}

include_once '../../actions.php';
//error_reporting(E_ALL);
function sendTranslationNoteEmail($baseMail, $to, $note, $attachmentsJson,$subject) {
    if (empty(trim(strip_tags($note)))) {
		$note = 'Note: This message was generated by the system. It may contain documents required to complete the assignment or assist you in doing so.';
	}

    $mail = clone $baseMail;
    $mail->clearAttachments(); // Clear previous attachments
    $mail->clearAllRecipients(); // Reset recipients

    $mail->addAddress($to);
    $mail->Subject = $subject;
    $mail->Body = $note;

    $fileArray = json_decode($attachmentsJson, true);
    if (is_array($fileArray)) {
        foreach ($fileArray as $file) {
            $path = 'files/attachments/' . $file;
            if (file_exists($path)) {
                $mail->addAttachment($path, $file);
            }
        }
    }

    $mail->send();
}

$update_id = @$_GET['update_id'];
$table = $_GET['table'];
$cron_tms = 0;
$createdBy = "";
if (isset($_GET['cron_tms']) && !empty($_GET['cron_tms'])) {
    $cron_tms = $_GET['cron_tms'];
}
$down = @$_GET['down'];
$emailto = @$_GET['emailto'];
$append_table = "";
$heading = "";
$timesheet_data = "";
$red_line = "";

$row = $obj->read_specific("$table.*,interpreter_reg.name,interpreter_reg.contactNo,interpreter_reg.country as interpreter_country,interpreter_reg.interp_pix,interpreter_reg.pic_updated,comp_reg.id as comp_id,comp_reg.name as company_name", "$table,interpreter_reg,comp_reg", "$table.intrpName = interpreter_reg.id AND $table.orgName = comp_reg.abrv AND $table.id=" . $update_id);
$supporting_doc_row = $obj->read_specific("*", "temp_supporting_documents", "order_id = $update_id ORDER BY id DESC LIMIT 1");
$supporting_note_html = '';
if (!empty($supporting_doc_row['note']) && $table != "translation") {
    $note = $supporting_doc_row['note'];
    $supporting_note_html = "<tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Supporting Note</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>$note</td>
    </tr>";
}

if ((isset($_SESSION['web_userId']) && $row['intrpName'] == $_SESSION['web_userId']) || isset($_SESSION['userId']) || $cron_tms==1) {
    $source = $row['source'];
    $target = $row['target'];
    $assignIssue = $row['assignIssue'];
    if ($cron_tms == 1) {
        $aloct_by = $row['aloct_by'];
        $createdBy = $obj->read_specific("login.id", "login", "login.name = '" . $aloct_by . "'")['id'];
    } elseif (isset($_SESSION['userId'])) {
        $createdBy = $_SESSION['userId'];
    }
    $orgRef = $row['orgRef'];
    $comp_id = $row['comp_id'];
    $orgName = $row['orgName'];
    $company_name = $row['company_name'];
    $nameRef = $row['nameRef'];
    $name = $row['name'];
	$s_subject = "{$source} - {$target} Ref {$nameRef}";
    $orgContact = $row['orgContact'];
    $remrks = $row['remrks'] ?: '';
    $inchPerson = $row['inchPerson'];
    $row['interp_pix'] = empty($row['interp_pix']) || $row['pic_updated'] == 0 ? "profile.png" : $row['interp_pix'];
    $image  = 'https://lsuk.org/lsuk_system/file_folder/interp_photo/' . $row['interp_pix'];
    $photo = $row['interp_pix'] ? '<img width="200" height="200" src="' . $image . '"/>' : "<br><br><br><p>Interpreter photo</p><br><br><br><br>";
    if ($table == 'translation') {
        $signature = '<tr><td class="td_no_border" width="100%"><span style="color:#000;font-size:14px;">Signature: </span>______________________________________ <span style="color:#000;font-size:14px;">Date: __________________________________</span></td></tr>';
    }
    if ($table == 'interpreter') {
        $sms_label = "F2F";
        $heading = "Interpreter Timesheet";
        $assignDate = $misc->dated($row['assignDate']);
        $db_assignDur = $row['assignDur'];
        $guess_dur = $row['guess_dur'];
        if ($db_assignDur > 60) {
            $hours = $db_assignDur / 60;
            if (floor($hours) > 1) {
                $hr = "hours";
            } else {
                $hr = "hour";
            }
            $mins = $db_assignDur % 60;
            if ($mins == 00) {
                $assignDur = sprintf("%2d $hr", $hours);
            } else {
                $assignDur = sprintf("%2d $hr %02d minutes", $hours, $mins);
            }
        } else if ($db_assignDur == 60) {
            $assignDur = "1 Hour";
        } else {
            $assignDur = $db_assignDur . " minutes";
        }
        if ($db_assignDur != $guess_dur && $guess_dur > 0) {
            //list($partdur1, $partdur2) = explode(':', $guess_dur);
            //$total_guess_dur = $partdur1 * 60 + $partdur2;
            if ($guess_dur > 60) {
                $guess_hours = $guess_dur / 60;
                if (floor($guess_hours) > 1) {
                    $guess_hr = "hours";
                } else {
                    $guess_hr = "hour";
                }
                $guess_mins = $guess_dur % 60;
                if ($guess_mins == 0) {
                    $get_guess_dur = sprintf("%2d $guess_hr", $guess_hours);
                } else {
                    $get_guess_dur = sprintf("%2d $guess_hr %02d minutes", $guess_hours, $guess_mins);
                }
            } else if ($guess_dur == 60) {
                $get_guess_dur = "1 Hour";
            } else {
                $get_guess_dur = $guess_dur . " minutes";
            }
        }
        $assignTime = $row['assignTime'];
        $buildingName = $row['buildingName'];
        $street = $row['street'];
        $assignCity = $row['assignCity'];
        $postCode = $row['postCode'];
        $interp_cat = $row['interp_cat'];
        $interp_type = $row['interp_type'];
        $write_interp_cat = $interp_cat == '12' ? $assignIssue : $obj->read_specific("ic_title", "interp_cat", "ic_id=" . $interp_cat)['ic_title'];
        $write_interp_type = $interp_cat == '12' ? '' : $obj->read_specific("GROUP_CONCAT(CONCAT(it_title)  SEPARATOR ' <b> & </b> ') as it_title", "interp_types", "it_id IN (" . $interp_type . ")")['it_title'];
        if ($interp_cat == '12') {
            $append_issue = "<tr><td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Category</td><td style='border: 1px solid yellowgreen;padding:5px;'>Other</td></tr><tr><td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Details</td><td style='border: 1px solid yellowgreen;padding:5px;'>" . $assignIssue . "</td></tr>";
        } else {
            $append_issue = "<tr><td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Category</td><td style='border: 1px solid yellowgreen;padding:5px;'>" . $write_interp_cat . "</td></tr><tr><td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Details</td><td style='border: 1px solid yellowgreen;padding:5px;'>" . $write_interp_type . "</td></tr>";
        }
        $strSubject = 'Timesheet ' . $assignDate . ' at ' . $assignTime . ' for Face To Face project id ' . $update_id;
        $append_table = "
        <table>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Source Language</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$source}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Target Language</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$target}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Date</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$assignDate}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Time</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$assignTime}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Duration</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$assignDur}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Location</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$buildingName}{$street}{$assignCity}{$postCode}</td>
        </tr>
        {$append_issue}
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Report to</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$inchPerson}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Case Worker or Person Incharge</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$orgContact}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Client Name</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$orgRef}</td>
        </tr>
        ".$supporting_note_html."
        </table>";
        if ($interp_cat == "6") {
            $append_table .= "<br>Please check the link below for the Glossary of mental health and wellbeing terms for interpreters to help you prepare for the session:<br>
            <a href='https://www.qld.gov.au/__data/assets/pdf_file/0023/508190/qtmhc-glossary-terms.pdf'>Glossary of mental health and wellbeing terms</a><br>";
        }
        if ($comp_id == 667 || $comp_id == 697 || $comp_id == 316 || $comp_id == 308) {
            // Part 1 + Part 2
            $append_table .= "<br>
            <p>
                Lateness due to issues with parking or traffic is not acceptable.
                <span style='color:#e03e2d; font-weight:bold;'>Doing Back-to-Back Jobs or Any Another Commitment?</span> Plan ahead, use an online route planner in advance, listen to local Radio to ensure you are aware of any <span style='color:#e03e2d; font-weight:bold;'> Ongoing Traffic Issues </span>. 
                Give Yourself sufficient time to walk to the assignment location and back to your car.<br><br>
                <span style='color:#e03e2d; font-weight:bold;'>Attending session at Southmead Hospital?</span> Parking might not be available at Hospital Sites. 
                <span style='color:#e03e2d; font-weight:bold;'>Park Free for 3 hours at Horfield Leisure Center and allow sufficient time to walk to the location.</span>
                Make Sure You Read / Understand and Comply with Parking Terms and Conditions.
            </p><br>";
        } elseif (in_array($comp_id, [534, 516, 892, 28, 613, 531])) {
            // Part 1 + Part 3
            $append_table .= "<br>
            <p>
                Lateness due to issues with parking or traffic is not acceptable.
                <span style='color:#e03e2d; font-weight:bold;'>Doing Back-to-Back Jobs or Any Another Commitment?</span> Plan ahead, use an online route planner in advance, listen to local Radio to ensure you are aware of any <span style='color:#e03e2d; font-weight:bold;'> Ongoing Traffic Issues </span>. 
                Give Yourself sufficient time to walk to the assignment location and back to your car.<br><br>
                <span style='color:#e03e2d; font-weight:bold;'>Attending session at Barton Hill Settlement?</span> East Bristol Liveable Neighbourhood scheme has been introduced to Barton Hill.Finding a Parking space may be difficult however, there is a parking at the bottom of the street.Please allow sufficient time to park and walk in order to arrive on time.
            </p><br>";
        } else {
            // Part 1 only
            $append_table .= "<br>
            <p>
                Lateness due to issues with parking or traffic is not acceptable.
                <span style='color:#e03e2d; font-weight:bold;'>Doing Back-to-Back Jobs or Any Another Commitment?</span> Plan ahead, use an online route planner in advance, listen to local Radio to ensure you are aware of any <span style='color:#e03e2d; font-weight:bold;'> Ongoing Traffic Issues </span>. 
                Give Yourself sufficient time to walk to the assignment location and back to your car.<br><br>
            </p><br>";
        }

        if($db_assignDur!=$guess_dur && $guess_dur>0){
            $append_table.="<br><u><b>NOTES FOR THIS JOB:</b></u><br>
            This session is booked for {$assignDur}, however it can take  up to {$get_guess_dur} or longer.<br>
            Therefore please consider your unrestricted availability before bidding / accepting this job.
            In cases of short notice cancellation, you will be paid the booked time ({$assignDur}).<br>";
            if (!empty($remrks)) {
                $append_table .= "{$remrks}<br>";
            }
        } else {
            if (!empty($remrks)) {
                $append_table .= "<br><u><b>NOTES FOR THIS JOB:</b></u><br>{$remrks}<br>";
            }
        }
        $orgContact = $row['orgContact'];
        $red_line = "Please return this form to Language Services UK Limited on the day of the assignment";
        $timesheet_data = '<h2 align="center" style="color:#0070c0;">Interpreter Timesheet – Face to Face Assignments</h2>
        <table class="table_first" width="100%" style="border:none !important;" cellspacing="0" cellpadding="0">
        <tbody>
        <tr>
            <td width="27%"  class="td_no_border">' . $photo . '</td>
            <td style="border:none !important;" width="75%">
                <table width="100%" style="border:none !important;" cellspacing="2" cellpadding="2"><tbody>
                <tr>
                    <td class="td_no_border" width="20%"><span style="color:#000;font-size:14px;">Linguist Name:</span></td><td class="td_no_border thin_border" width="75%" align="center"><span>' . $name . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="15%"><span style="color:#000;font-size:14px;">LSUK - Ref:</span></td><td class="td_no_border thin_border" width="30%"><span>' . $nameRef . '</span></td>
                    <td class="td_no_border" width="15%"><span style="color:#000;font-size:14px;">Client - Ref:</span></td><td class="td_no_border thin_border" width="35%"><span>' . $orgRef . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="15%"><span style="color:#000;font-size:14px;">Language:</span></td><td class="td_no_border thin_border" width="30%"><span>' . $source . '</span></td>
                    <td class="td_no_border" width="10%"><span style="color:#000;font-size:14px;">Dialect:</span></td><td class="td_no_border thin_border" width="40%"><span>' . $target . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="21%"><span style="color:#000;font-size:14px;">Assignment Date:</span></td><td class="td_no_border thin_border" width="25%"><span>' . $assignDate . '</span></td>
                    <td class="td_no_border" width="22%"><span style="color:#000;font-size:14px;">Assignment Time:</span></td><td class="td_no_border thin_border" width="18%"><span>' . $assignTime . '</span></td><td class="td_no_border" width="11%"><span>PM/AM</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="48%"><span style="color:#000;font-size:14px;">Assignment Duration (Minimum Duration):</span></td><td class="td_no_border thin_border" width="48%"><span>' . $assignDur . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Interpreter Contact:</span></td><td class="td_no_border thin_border" width="73%"><span>' . $orgContact . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Organization Name:</span></td><td class="td_no_border thin_border" width="73%"><span>' . $company_name . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="24%"><span style="color:#000;font-size:14px;">Place of Assignment:</span></td><td class="td_no_border thin_border" width="73%"><span>' . $buildingName . '  ' . $street . '  ' . $assignCity . '  ' . $postCode . '</span></td>
                </tr>
                </tbody>
                </table>
            </td>
        </tr>
        </tbody></table><h3 style="color:#0070c0;margin:0px !important;padding:0px !important;">Actual Hours</h3>
        <table class="table_first" width="100%" style="border:none !important;" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
            <td style="border:none !important;" width="100%">
                <table style="border:none !important;" cellspacing="2" cellpadding="1"><tbody>
                <tr>
                    <td class="td_no_border" width="13%"><span style="color:#000;font-size:14px;"><b>Arrival Time:</b></span></td><td class="td_no_border thin_border" width="16%"><span></span></td><td class="td_no_border" width="15%"><span><b>PM/AM</b></span></td>
                    <td class="td_no_border" width="20%"><span style="color:#000;font-size:14px;"><b>Waiting Time (if any):</b></span></td><td class="td_no_border thin_border" width="17%"><span></span></td><td class="td_no_border" width="16%"><span><b>Hours / Minutes</b></span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="10%"><span style="color:#000;font-size:14px;">Start Time:</span></td><td class="td_no_border thin_border" width="11%"><span></span></td><td class="td_no_border" width="12%"><span>PM/AM</span></td>
                    <td class="td_no_border" width="12%"><span style="color:#000;font-size:14px;">Finish Time:</span></td><td class="td_no_border thin_border" width="11%"><span></span></td><td class="td_no_border" width="12%"><span>PM/AM</span></td>
                    <td class="td_no_border" width="13%"><span style="color:#000;font-size:14px;">Total Duration:</span></td><td class="td_no_border thin_border" width="15%"><span></span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="27%"><span style="color:#000;font-size:14px;">Travel Duration (if Applicable):</span></td><td class="td_no_border thin_border" width="10%"><span></span></td><td class="td_no_border" width="17%"><span>Hours / Minutes</span></td>
                    <td class="td_no_border" width="17%"><span style="color:#000;font-size:14px;">Mode of Transport:</span></td><td class="td_no_border thin_border" width="26%"><span></span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="27%"><span style="color:#000;font-size:14px;">Travel Mileage (if Applicable):</span></td><td class="td_no_border thin_border" width="10%"><span></span></td><td class="td_no_border" width="17%"><span>Miles</span></td>
                    <td class="td_no_border" width="34%"><span style="color:#000;font-size:14px;">Other Expenses (Parking, Bridge Toll) £:</span></td><td class="td_no_border thin_border" width="9%"><span></span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="27%"><span style="color:#000;font-size:14px;">Travel Costs (If Applicable) £:</span></td><td class="td_no_border thin_border" width="10%"><span></span></td>
                    <td class="td_no_border" width="30%"><span style="color:#000;font-size:14px;">Please Attach Receipts</span></td>
                </tr>
                </tbody>
                </table>
            </td>
        </tr>
        </tbody></table>
        <style>table, td, th {border: 1px solid grey;} .custom_space{margin-bottom:5px;}</style>
         <table class="custom_space" style="border-collapse: collapse; width: 100%;  max-width: 600px;">
            <thead>
                <tr>
                    <th style="padding: 2px; border: 0px solid grey; text-align: center; font-weight: bold;" colspan="4">Feedback</th>
                </tr>
                <tr>
                    <th style=" padding: 2px;    text-align: left; width: 25%;"></th>
                    <th style=" padding: 2px;    text-align: center; width: 25%;">Poor</th>
                    <th style=" padding: 2px;    text-align: center; width: 25%;">Good</th>
                    <th style=" padding: 2px;    text-align: center; width: 25%;">Excellent</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style=" padding: 2px; ">Professionalism</td>
                    <td style=" padding: 2px;"></td>
                    <td style=" padding: 2px;"></td>
                    <td style=" padding: 2px;"></td>
                </tr>
                <tr>
                    <td style=" padding: 2px; ">Impartiality</td>
                    <td style=" padding: 2px;"></td>
                    <td style=" padding: 2px;"></td>
                    <td style=" padding: 2px;"></td>
                </tr>
                <tr>
                    <td style=" padding: 2px; ">Appearance</td>
                    <td style=" padding: 2px;"></td>
                    <td style=" padding: 2px;"></td>
                    <td style=" padding: 2px;"></td>
                </tr>
                <tr>
                    <td style=" padding: 2px; " colspan="2">Punctuality -<br>Was the Interpreter Late? &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Yes / No</td>
                    <td style=" padding: 2px; text-align: left;" colspan="2">If Yes, How Many Minutes?</td>
                    
                </tr>
                <tr>
                    <td style=" padding: 20px; ">Comments (if any)</td>
                    <td style=" padding: 20px;" colspan="3"><br><br></td>
                </tr>
            </tbody>
        </table>
        <table width="100%"  cellspacing="0" cellpadding="4">
        <tbody>
            <tr>
                <td class="td_no_border" width="100%"><span style="color:#000;font-size:14px;"><b>Authorised Signatory</b></span></td>
            </tr>
            <tr>
                <td class="td_no_border" width="100%"><span style="color:#000;font-size:14px;">Client Signature: ___________________________________________</span></td>
            </tr>
            <tr>
                <td class="td_no_border" width="100%"><span style="color:#000;font-size:14px;">Name: ___________________________________________</span> <span style="color:#000;font-size:14px;">Designation: _______________________________________</span></td>
            </tr>
            <tr>
                <td class="td_no_border" width="100%" style="margin-bottom:0px;padding-bottom:0px;"><span style="color:#000;font-size:13px;">“I am an authorised signatory for my department. I am signing to confirm that the Interpreter and the hours that I am
                authorising are accurate and I approve payment. I am signing to confirm that I have checked and verified the photo
                identification of the interpreter with the booking form/job card. I understand that if I knowingly provide false
                information this may result in disciplinary action and I may be liable to prosecution and civil recovery proceedings. I
                consent to the disclosure of information from this form to and by the Approved Organisation for the purpose of
                verification of this claim and the investigation, prevention, detection and prosecution of fraud.”</span></td>
            </tr>
            ' . $signature . '
        </tbody>
        </table><br>
                <span style="color:#000;font-size:13px;margin-top:5px; padding:5px 0px 3px px;">“I declare that the information I have given on this form is correct and complete and that I have not claimed elsewhere
                under this agreement for the hours/shifts detailed on this timesheet. I understand that if I knowingly provide false
                information this may result in disciplinary action and I may be liable to prosecution and civil recovery proceedings. I
                consent to the disclosure of information from this form to and by the Approved Organisation for the purpose of verification
                of this claim and the investigation, prevention, detection and prosecution of fraud.”</span>
        <br><b>Interpreter Signature:</b></span><span>____________________________________</span> <b>Date:</b><span>__________________________________</span><br>
        Future Booking Date (if Known) <b>Date: </b></span><span>_______________________</span> <b>Time:</b><span>________________________</span><br>
        <b>Location (if different):</b></span><span>_________________________________________________________________</span><br>
        <b>I can / can’t Attend the future session?</b></span><span> Yes / No</span><br>
        <span style="color:red;font-size:14px;" align="center"><br><b>' . $red_line . '</b></span>';
        $timesheet_body = $obj->read_specific("em_format", "email_format", "id=2")['em_format'];
        $data   = ["[NAME]", "[SOURCE]", "[BUILDINGNAME]", "[STREET]", "[ASSIGNCITY]", "[POSTCODE]", "[ASSIGNDATE]", "[ASSIGNTIME]", "[APPENDTABLE]"];
        $to_replace  = ["$name", "$source", "$buildingName", "$street", "$assignCity", "$postCode", "$assignDate", "$assignTime", "$append_table"];
    } else if ($table == 'telephone') {
        $db_assignDur = $row['assignDur'];
        $guess_dur = $row['guess_dur'];
        if ($db_assignDur > 60) {
            $hours = $db_assignDur / 60;
            if (floor($hours) > 1) {
                $hr = "hours";
            } else {
                $hr = "hour";
            }
            $mins = $db_assignDur % 60;
            if ($mins == 00) {
                $assignDur = sprintf("%2d $hr", $hours);
            } else {
                $assignDur = sprintf("%2d $hr %02d minutes", $hours, $mins);
            }
        } else if ($db_assignDur == 60) {
            $assignDur = "1 Hour";
        } else {
            $assignDur = $db_assignDur . " minutes";
        }
        if ($db_assignDur != $guess_dur) {
            if ($guess_dur > 60) {
                $guess_hours = $guess_dur / 60;
                if (floor($guess_hours) > 1) {
                    $guess_hr = "hours";
                } else {
                    $guess_hr = "hour";
                }
                $guess_mins = $guess_dur % 60;
                if ($guess_mins == 0) {
                    $get_guess_dur = sprintf("%2d $guess_hr", $guess_hours);
                } else {
                    $get_guess_dur = sprintf("%2d $guess_hr %02d minutes", $guess_hours, $guess_mins);
                }
            } else if ($guess_dur == 60) {
                $get_guess_dur = "1 Hour";
            } else {
                $get_guess_dur = $guess_dur . " minutes";
            }
        }
        $assignDate = $misc->dated($row['assignDate']);
        $assignTime = $row['assignTime'];
        $telep_cat = $row['telep_cat'];
        $telep_type = $row['telep_type'];
        $write_telep_cat = $telep_cat == '11' ? $assignIssue : $obj->read_specific("tpc_title", "telep_cat", "tpc_id=" . $telep_cat)['tpc_title'];
        $write_telep_type = $telep_cat == '11' ? '' : $obj->read_specific("GROUP_CONCAT(CONCAT(tpt_title)  SEPARATOR ' <b> & </b> ') as tpt_title", "telep_types", "tpt_id IN (" . $telep_type . ")")['tpt_title'];
        if ($telep_cat == '11') {
            $append_issue = "<tr><td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Category</td><td style='border: 1px solid yellowgreen;padding:5px;'>Other</td></tr><tr><td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Details</td><td style='border: 1px solid yellowgreen;padding:5px;'>" . $assignIssue . "</td></tr>";
        } else {
            $append_issue = "<tr><td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Category</td><td style='border: 1px solid yellowgreen;padding:5px;'>" . $write_telep_cat . "</td></tr><tr><td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Details</td><td style='border: 1px solid yellowgreen;padding:5px;'>" . $write_telep_type . "</td></tr>";
        }
        $comunic = $obj->read_specific("c_title", "comunic_types", "c_id=" . $row['comunic'])['c_title'];
        // $channel_img = file_exists('../../images/comunic_types/' . $get_channel['c_image']) ? '<img src="../../images/comunic_types/' . $get_channel['c_image'] . '" width="36"/> ' : '';
        $communication_type = empty($row['comunic']) || $row['comunic'] == 11 ? "Telephone interpreting" : $comunic;
        $sms_label = $communication_type;
        $heading = $communication_type . " Timesheet";
        $supporting_Note=$supporting_doc_row['note'];
        $strSubject = 'Timesheet ' . $assignDate . ' at ' . $assignTime . ' for ' . $communication_type . ' project id ' . $update_id;
        $append_table = "
        <table>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Communication Type</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$comunic}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Source Language</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$source}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Target Language</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$target}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Date</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$assignDate}</td>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Time</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$assignTime}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Assignment Duration</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$assignDur}</td>
        </tr>
        {$append_issue}
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Report to</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$inchPerson}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Case Worker</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$orgContact}</td>
        </tr>
        ".$supporting_note_html."
        </table>";
        if ($telep_cat == "6") {
            $append_table .= "<br>Please check the link below for the Glossary of mental health and wellbeing terms for interpreters to help you prepare for the session:<br>
            <a href='https://www.qld.gov.au/__data/assets/pdf_file/0023/508190/qtmhc-glossary-terms.pdf'>Glossary of mental health and wellbeing terms</a><br>";
        }
        if ($db_assignDur != $guess_dur && $guess_dur > 0) {
            $append_table .= "<br><u><b>NOTES FOR THIS JOB:</b></u><br>
            This session is booked for {$assignDur}, however it can take  up to {$get_guess_dur} or longer.<br>
            Therefore please consider your unrestricted availability before bidding / accepting this job.
            In cases of short notice cancellation, you will be paid the booked time ({$assignDur}).<br>";
            if (!empty($remrks)) {
                $append_table .= "{$remrks}<br>";
            }
        } else {
            if (!empty($remrks)) {
                $append_table .= "<br><u><b>NOTES FOR THIS JOB:</b></u><br>{$remrks}<br>";
            }
        }
        $red_line = "Please return this form to Language Services UK Limited straight after the assignment";
        $timesheet_data = '<br><h2 align="center" style="color:#0070c0;">Interpreter Timesheet – ' . $communication_type . ' Assignments</h2><br>
            <table class="table_first" width="100%" style="height:400px;border:none !important;" cellspacing="8" cellpadding="4">
            <tbody>
            <tr>
                <td style="border:none !important;" width="100%">
                    <table width="100%" style="border:none !important;" cellspacing="8" cellpadding="4"><tbody>
                    <tr>
                        <td class="td_no_border" width="17%"><span style="color:#000;font-size:14px;">Linguist Name:</span></td><td class="td_no_border thin_border" width="76%" align="center"><span>' . $name . '</span></td>
                    </tr>
                    <tr>
                        <td class="td_no_border" width="13%"><span style="color:#000;font-size:14px;">LSUK - Ref:</span></td><td class="td_no_border thin_border" width="30%"><span>' . $nameRef . '</span></td>
                        <td class="td_no_border" width="13%"><span style="color:#000;font-size:14px;">Client - Ref:</span></td><td class="td_no_border thin_border" width="35%"><span>' . $orgRef . '</span></td>
                    </tr>
                    <tr>
                        <td class="td_no_border" width="13%"><span style="color:#000;font-size:14px;">Language:</span></td><td class="td_no_border thin_border" width="30%"><span>' . $source . '</span></td>
                        <td class="td_no_border" width="13%"><span style="color:#000;font-size:14px;">Dialect:</span></td><td class="td_no_border thin_border" width="35%"><span>' . $target . '</span></td>
                    </tr>
                    <tr>
                        <td class="td_no_border" width="18%"><span style="color:#000;font-size:14px;">Assignment Date:</span></td><td class="td_no_border thin_border" width="25%"><span>' . $assignDate . '</span></td>
                        <td class="td_no_border" width="20%"><span style="color:#000;font-size:14px;">Assignment Time:</span></td><td class="td_no_border thin_border" width="19%"><span>' . $assignTime . '</span></td><td class="td_no_border" width="11%"><span>PM/AM</span></td>
                    </tr>
                    <tr>
                        <td class="td_no_border" width="40%"><span style="color:#000;font-size:14px;">Assignment Duration (Minimum Duration):</span></td><td class="td_no_border thin_border" width="55%"><span>' . $assignDur . '</span></td>
                    </tr>
                    <tr>
                        <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Interpreter Contact:</span></td><td class="td_no_border thin_border" width="73%"><span>' . $orgContact . '</span></td>
                    </tr>
                    <tr>
                        <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Organization Name:</span></td><td class="td_no_border thin_border" width="73%"><span>' . $company_name . '</span></td>
                    </tr>
                    </tbody>
                    </table>
                </td>
            </tr>
            </tbody></table><br><h3 style="color:#0070c0;">&nbsp;&nbsp;&nbsp;Actual Hours</h3><br>
            <table class="table_first" width="100%" style="height:400px;border:none !important;" cellspacing="0" cellpadding="0">
            <tbody>
                <tr>
                <td style="border:none !important;" width="100%">
                    <table style="border:none !important;" cellspacing="2" cellpadding="2">
                    <tbody>
                    <tr>
                        <td class="td_no_border" width="20%"><span style="color:#000;font-size:14px;"><b>Waiting Time (if any):</b></span></td><td class="td_no_border thin_border" width="17%"><span></span></td><td class="td_no_border" width="16%"><span><b>Hours / Minutes</b></span></td>
                    </tr>
                    <tr>
                        <td class="td_no_border" width="20%"></td>
                    </tr>
                    <tr>
                        <td class="td_no_border" width="10%"><span style="color:#000;font-size:14px;">Start Time:</span></td><td class="td_no_border thin_border" width="8%"><span></span></td><td class="td_no_border" width="12%"><span>PM/AM</span></td>
                        <td class="td_no_border" width="11%"><span style="color:#000;font-size:14px;">Finish Time:</span></td><td class="td_no_border thin_border" width="8%"><span></span></td><td class="td_no_border" width="12%"><span>PM/AM</span></td>
                        <td class="td_no_border" width="13%"><span style="color:#000;font-size:14px;">Total Duration:</span></td><td class="td_no_border thin_border" width="10%"><span></span></td><td class="td_no_border" width="8%"><span><b>Hours</b></span></td>
                    </tr>
                    </tbody>
                    </table>
                </td>
            </tr>
            </tbody></table><br><br>
            <style>table, td, th {border: 1px solid grey;}</style>
            <table width="100%" style="height:400px;border:none;" cellspacing="0" cellpadding="12">
            <tbody>
                <tr>
                    <td class="td_no_border" width="100%"><span style="color:#000;font-size:16px;">“I declare that the information I have given on this form is correct and complete and that I have not claimed elsewhere 
                    under this agreement for the hourr detailed on this timesheet. I understand that if I knowingly provide false information 
                    this may result in disciplinary action and I may be liable to prosecution and civil recovery proceedings. I consent to the 
                    disclosure of information from this form to and by the Approved Organisation for the purpose of verification of this claim 
                    and the investigation, prevention, detection and prosecution of fraud.”</span></td>
                </tr>
            </tbody>
            </table>
            <b>&nbsp;&nbsp;&nbsp;Interpreter Signature:</b></span><span>____________________________________</span> <b>Date:</b><span>______________________________</span><br><br>
            &nbsp;&nbsp;&nbsp;Future Booking Date (if Known) <b>Date: </b></span><span>_______________________</span> <b>Time:</b><span>________________________</span><br><br><br>
            &nbsp;&nbsp;&nbsp;<b>I can / can’t Attend the future session?</b></span><span> Yes / No</span>
            <span style="color:red;font-size:14px;" align="center"><b>' . $red_line . '</b></span>';
        $timesheet_body = $obj->read_specific("em_format", "email_format", "id=51")['em_format'];
        $data   = ["[NAME]", "[SOURCE]", "[ASSIGNDATE]", "[ASSIGNTIME]", "[APPENDTABLE]"];
        $to_replace  = ["$name", "$source", "$assignDate", "$assignTime", "$append_table"];
    } else {
        $sms_label = "Translation";
        $heading = "Translation Timesheet";
        $assignDate = $misc->dated($row['asignDate']);
        $docType = $obj->read_specific("tc_title", "trans_cat", "tc_id=" . $row['docType'])['tc_title'];
        $transType = $obj->read_specific("GROUP_CONCAT(CONCAT(td_title)  SEPARATOR ' <b> & </b> ') as td_title", "trans_dropdown", "td_id IN (" . $row['transType'] . ")")['td_title'];
        $trans_detail = $obj->read_specific("GROUP_CONCAT(CONCAT(tt_title)  SEPARATOR ' <b> & </b> ') as tt_title", "trans_types", "tt_id IN (" . $row['trans_detail'] . ")")['tt_title'];
        $deliveryType = $row['deliveryType'];
        $deliverDate2 = $misc->dated($row['deliverDate2']);
        $strSubject = 'Timesheet ' . $assignDate . ' for ' . $sms_label . ' project id ' . $update_id;
        $append_table = "
        <table>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Source Language</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$source}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Target Language</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$target}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Document Type</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$docType}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Translation Type(s)</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$trans_detail}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Translation Category</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$transType}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Delivery Date</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$deliverDate2}</td>
        </tr>
        <tr>
        <td style='border: 1px solid yellowgreen;padding:5px;'>Delivery Type</td>
        <td style='border: 1px solid yellowgreen;padding:5px;'>{$deliveryType}</td>
        </tr>
        </table>";
        if (!empty($remrks)) {
            $append_table .= "<br>{$remrks}<br>";
        }
        $timesheet_data = '<div style="font-size:12px"><span style="font-weight:bold;color:#066;">Name:</span><u>&nbsp;&nbsp;&nbsp;' . $name . '&nbsp;&nbsp;</u><span style="color:#FFF; font-size:7px">_________</span><span style="font-weight:bold;color:#066">Source Language:</span><u>&nbsp;&nbsp;&nbsp;' . $source . '&nbsp;&nbsp;</u><span style="color:#FFF; font-size:7px">_________</span><span style="font-weight:bold;color:#066">Target Language:</span><u>&nbsp;&nbsp;&nbsp;' . $target . '&nbsp;&nbsp;</u><span style="color:#FFF; font-size:7px">_________</span></div><br>

        <div style="font-size:12px"><span style="font-weight:bold;color:#066;">Date of Assignment:</span><u>&nbsp;&nbsp;&nbsp;' . $assignDate . '&nbsp;&nbsp;</u><span style="color:#FFF; font-size:7px">_________</span><span style="font-weight:bold;color:#066">Delivery Date:</span><u>&nbsp;&nbsp;&nbsp;' . $deliverDate2 . '&nbsp;&nbsp;</u><span style="color:#FFF; font-size:7px">_________</span><span style="font-weight:bold;color:#066">Submission Date:</span><span style="font-size:7px">________________________</span></div><br>

        <div style="font-size:12px"><span style="font-weight:bold;color:#066;">Project ID:</span><u>&nbsp;' . $nameRef . '&nbsp;</u><span style="color:#FFF; font-size:7px">_____</span><span style="font-weight:bold;color:#066">Assignment Type:</span><u>&nbsp;' . $docType . '&nbsp;</u><span style="color:#FFF; font-size:7px">_____</span><br><br><span style="font-weight:bold;color:#066">Translation Category:</span><u>&nbsp;&nbsp;&nbsp;' . $transType . '&nbsp;&nbsp;</u><span style="color:#FFF; font-size:7px">_______</span><br><br><span style="font-weight:bold;color:#066">Translation Type(s):</span><u>&nbsp;&nbsp;&nbsp;' . $trans_detail . '&nbsp;&nbsp;</u><span style="color:#FFF; font-size:7px">_______</span></div><br>

        <div style="font-size:12px"><span style="font-weight:bold;color:#066;">Source Language Word Count:</span><span style="font-size:7px">______________________________________ </span><span style="font-weight:bold;color:#066;"> Target Language Word Count: </span><span style="font-size:7px">______________________________</span></div><br>

        <div style="border:1px solid #C30">

        <div style="font-size:12px"><span style="font-weight:bold;color:#066;"> Company / Team / Unit Name or Title: </span> <u>' . $company_name . ' </u></div><br>



        <div style="font-size:12px"><span style="font-weight:bold;color:#066;"> Contact Name:</span><u>' . $orgContact . '</u></div><br>

        </div>
        <br/>
        <div style="font-size:14px;line-height:30px">I hereby certify that I, [<u><i> ' . $name . ' </i></u>], am a professional translator to LSUK Limited. I hereby declare that I, am
        fully conversant with the [ ' . $source . ' ] and the [ ' . $target . ' ] translation languages and that the
        attached is translation in [ ' . $target . ' ] from [ ' . $source . ' ].
        I can confirm that this translation is to the best of my knowledge and belief, a true and faithful rendering of
        the original [ ' . $source . ' ] document and is translated to the best of my ability as a professional translator.
        Nothing is added or omitted to / from this document.<br><br>Executed on</span></div>';
        $red_line = "Please return this form to Language Services UK Limited along with the translation. Thank You";
        $timesheet_data = '<br><h2 align="center" style="color:#0070c0;">Interpreter Timesheet – Translation Assignments</h2><br>
        <table class="table_first" width="100%" style="height:400px;border:none !important;" cellspacing="8" cellpadding="4">
        <tbody>
        <tr>
            <td style="border:none !important;" width="100%">
                <table width="100%" style="border:none !important;" cellspacing="8" cellpadding="4"><tbody>
                <tr>
                    <td class="td_no_border" width="17%"><span style="color:#000;font-size:14px;">Linguist Name:</span></td><td class="td_no_border thin_border" width="76%" align="center"><span>' . $name . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="18%"><span style="color:#000;font-size:14px;">LSUK - Ref:</span></td><td class="td_no_border thin_border" width="27%"><span>' . $nameRef . '</span></td>
                    <td class="td_no_border" width="14%"><span style="color:#000;font-size:14px;">Client - Ref:</span></td><td class="td_no_border thin_border" width="32%"><span>' . $orgRef . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="18%"><span style="color:#000;font-size:14px;">Language:</span></td><td class="td_no_border thin_border" width="27%"><span>' . $source . '</span></td>
                    <td class="td_no_border" width="14%"><span style="color:#000;font-size:14px;">Dialect:</span></td><td class="td_no_border thin_border" width="32%"><span>' . $target . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="18%"><span style="color:#000;font-size:14px;">Assignment Date:</span></td><td class="td_no_border thin_border" width="27%"><span>' . $assignDate . '</span></td>
                    <td class="td_no_border" width="17%"><span style="color:#000;font-size:14px;">Delivery Date:</span></td><td class="td_no_border thin_border" width="29%"><span>' . $deliverDate2 . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Submission Date:</span></td><td class="td_no_border thin_border" width="70%"><span></span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Assignment Type:</span></td><td class="td_no_border thin_border" width="70%"><span>' . $docType . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Translation Category:</span></td><td class="td_no_border thin_border" width="70%"><span>' . $transType . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Translation Type(s):</span></td><td class="td_no_border thin_border" width="70%"><span>' . $trans_detail . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Interpreter Contact:</span></td><td class="td_no_border thin_border" width="70%"><span>' . $orgContact . '</span></td>
                </tr>
                <tr>
                    <td class="td_no_border" width="23%"><span style="color:#000;font-size:14px;">Organization Name:</span></td><td class="td_no_border thin_border" width="70%"><span>' . $company_name . '</span></td>
                </tr>
                </tbody>
                </table>
            </td>
        </tr>
        </tbody></table>
        <br><h3 style="color:#0070c0;">&nbsp;&nbsp;&nbsp;Actual Units / Words Count</h3><br>
        <table class="table_first" width="100%" style="height:400px;border:none !important;" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td class="td_no_border" width="20%"></td>
            </tr>
            <tr>
                <td class="td_no_border" width="30%"><span style="color:#000;font-size:15px;"><b>&nbsp;&nbsp;&nbsp;Source Language Word Count</b></span></td><td class="td_no_border thin_border" width="18%"><span></span></td>
                <td class="td_no_border" width="29%"><span style="color:#000;font-size:15px;"><b>Target Language Word Count</b></span></td><td class="td_no_border thin_border" width="18%"><span></span></td>
            </tr>
            <tr>
                <td class="td_no_border" width="20%"></td>
            </tr>
        </tbody></table>
        <br><br>
        <style>table, td, th {border: 1px solid grey;}</style>
        <table width="100%" style="border:none;" cellspacing="0" cellpadding="8">
        <tbody>
            <tr>
                <td class="td_no_border" width="100%"><span style="color:#000;font-size:16px;">“I hereby certify that I, [<u><i> ' . $name . ' </i></u>], am a professional translator to LSUK Limited. I hereby declare that I, am
        fully conversant with the [ ' . $source . ' ] and the [ ' . $target . ' ] translation languages and that the
        attached is translation in [ ' . $target . ' ] from [ ' . $source . ' ].
        I can confirm that this translation is to the best of my knowledge and belief, a true and faithful rendering of
        the original [ ' . $source . ' ] document and is translated to the best of my ability as a professional translator.
        Nothing is added or omitted to / from this document.”<br><br>Executed on</span></td>
            </tr>
        </tbody>
        </table><br><br>
        <b>&nbsp;&nbsp;&nbsp;Interpreter Signature:</b></span><span>____________________________________</span> <b>Date:</b><span>______________________________</span><br><br>
        <span style="color:red;font-size:14px;" align="center"><br><b>' . $red_line . '</b></span>';
        $timesheet_body = $obj->read_specific("em_format", "email_format", "id=30")['em_format'];
        $data   = ["[NAME]", "[SOURCE]", "[ASSIGNDATE]", "[APPENDTABLE]"];
        $to_replace  = ["$name", "$source", "$assignDate", "$append_table"];
    }
    require_once 'tcpdf_include.php';

    // create new PDF document
    $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    // set document information
    $pdf->SetCreator(PDF_CREATOR);
    // set default header data
    //include 'rip_header.php';
    $PDF_HEADER_LOGO = "logo.png"; //any image file. check correct path.
    $PDF_HEADER_LOGO_WIDTH = "10";
    $PDF_HEADER_TITLE = "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLanguage Services UK Limited";
    $PDF_HEADER_STRING = "\t\t\t\t\t\t\t\tInterpreting | Translation | Telephone Interpreting | Cross-Cultural Training & More";
    $pdf->SetHeaderData($PDF_HEADER_LOGO, $PDF_HEADER_LOGO_WIDTH, $PDF_HEADER_TITLE, $PDF_HEADER_STRING);
    $pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    include 'rip_footer.php'; // set header and footer fonts
    $pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
    // set default monospaced font
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
    // set margins
    $pdf->SetMargins(4, 13, 4);
    $pdf->SetHeaderMargin(1);
    $pdf->SetFooterMargin(8);

    // set auto page breaks
    $pdf->SetAutoPageBreak(false, PDF_MARGIN_BOTTOM);

    // set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

    // set some language-dependent strings (optional)
    if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
        require_once dirname(__FILE__) . '/lang/eng.php';
        $pdf->setLanguageArray($l);
    }
    //$pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFont('Times');
    $pdf->AddPage();
    $tbl = "<style>.td_no_border{border:none !important;}.thin_border{border-bottom:1px;border-bottom-color:grey;border-bottom-width:1px;font-style:italic;}</style>{$timesheet_data}";

    $pdf->writeHTML($tbl, true, false, false, false, '');

    // $pdf->Output('', 'I'); die;
    // Footer new data
    //$this->SetX($this->original_lMargin);
    // $this->Cell(0, 0, 'Address: Suite 3, Davis House, Lodge Causeway Trading Estate, Lodge Causeway, Fishponds, Bristol BS16 3JB.', 'T', 0, 'C');
    // $this->Ln();
    // $this->Cell(0, 0, 'Phone 01173290610, Mob: 07915177068 Fax: 0333 800 5785 Email: PAYROLL@LSUK.ORG', 'T', 0, 'C');

    $new_name = explode(':', $assignTime);
    $new_filename = $new_name[0] . '_' . $new_name[1] . '_' . $new_name[2];
    $name_file = $table != 'translation' ? "Timesheet $assignDate at $new_filename.pdf" : "Timesheet $assignDate.pdf";

    //Send SMS if LSUK Admin hit the link
    if (!empty($createdBy) && $_GET['send_sms'] == 1) {
        $array_order_types = array("interpreter" => 1, "telephone" => 2, "translation" => 3);
        $get_application = $obj->read_specific("*", "job_messages", "order_type=" . $array_order_types[$table] . " AND order_id=" . $row['id'] . " AND interpreter_id=" . $row['intrpName'] . " AND message_category=2");
        if (empty($get_application['id'])) {
            //Adding config for SMS
            include '../../../source/setup_sms.php';
            $setupSMS = new setupSMS;
            $interpreter_phone = $setupSMS->format_phone($row['contactNo'], $row['interpreter_country']);
            $appendTime = $table != 'translation' ? $assignTime : "";
            $message_body = "Hi\nYou have been allocated\n" . $sms_label . " Job ID:" . $row['id'] . "\nDate / Time:" . $assignDate . " " . $appendTime . "\nDuration:" . $assignDur . "\nTo View / Download Timesheet please use LSUK App / Portal".($row['comp_id'] == 667 ? "\nParking Lateness is not Acceptable" : "");
            $sms_response = $setupSMS->send_sms($interpreter_phone, $message_body);
            $obj->insert("job_messages", array("order_id" => $row['id'], "order_type" => $array_order_types[$table], "message_category" => 2, "interpreter_id" => $row['intrpName'], "created_by" => $createdBy, "message_body" => $message_body, "sent_to" => $interpreter_phone));
            $inserted_id = $obj->con->insert_id;
            if ($inserted_id) {
                if ($sms_response['status'] == 0) {
                    $obj->update("job_messages", array("status" => 0), "id=" . $inserted_id);
                }
            }
        }
    }

    if (!isset($down) || isset($emailto)) {

        $pdfhere = $pdf->Output('', 'S');
        //echo $pdfhere;
        $to_add = $emailto;
        $strMsg = str_replace($data, $to_replace, $timesheet_body);
        try {
            $mail->SMTPDebug = 0;
            $mail->isSMTP();
            $mail->Host = setupEmail::EMAIL_HOST;
            $mail->SMTPAuth   = true;
            $mail->Username   = setupEmail::PAYROLL_EMAIL;
            $mail->Password   = setupEmail::PAYROLL_PASSWORD;
            $mail->SMTPSecure = setupEmail::SECURE_TYPE;
            $mail->Port       = setupEmail::SENDING_PORT;
            $mail->setFrom($from_add, $from_name, 0);
            $mail->addAddress($to_add);
            $mail->addReplyTo($from_add, $from_name);
            $mail->isHTML(true);
            $mail->Subject = $strSubject;
            $mail->Body    = $strMsg;
            $fileArray = json_decode($supporting_doc_row["files_address"], true);
			if (is_array($fileArray)  && $table != "translation" ) {
				foreach ($fileArray as $file) {
					$path = 'files/attachments/' . $file;
					if (file_exists($path)) {
						 $mail->addAttachment($path, $file);
					}
				}
			}
			if ($table == "translation" && (!empty(trim(strip_tags($supporting_doc_row["note"]))) || !empty($supporting_doc_row["files_address"]) && $supporting_doc_row["files_address"] !== '[]')) {
					sendTranslationNoteEmail($mail, $to_add, $supporting_doc_row['note'], $supporting_doc_row['files_address'],$s_subject);
				}
            $mail->addStringAttachment($pdfhere, $name_file);
            if ($orgName != "" && substr($company_name, 0, 3) == 'VHS') {
                $mail->addAttachment('files/Questionnaires_MDS_for_VHS.pdf', 'Questionnaire.pdf');
            }
            if ($mail->send()) {
                $mail->ClearAllRecipients();
                $mail->ClearAttachments();
                $mail->addAddress($to_lsuk);
                $mail->addReplyTo($from_add, $from_name);
                $mail->isHTML(true);
                $mail->Subject = $strSubject;
                $mail->Body    = $strMsg;
                $mail->addStringAttachment($pdfhere, $name_file);
                if ($orgName != "" && substr($company_name, 0, 3) == 'VHS') {
                    $mail->addAttachment('files/Questionnaires_MDS_for_VHS.pdf', 'Questionnaire.pdf');
                }
                if ($mail->send()) {
                    $mail->ClearAllRecipients();
                    $mail->ClearAttachments();
                    list($a, $b) = explode('.', basename(__FILE__));
                    $pdf->Output('', 'I');
                } else {
                    echo "Mailer Error: " . $mail->ErrorInfo;
                }
            }
        } catch (Exception $e) {
            echo "<center><h3>The timesheet could not be sent via email.<br>Kindly send it manually.<br><a href='new_timesheet.php?update_id=" . $update_id . "&table=" . $table . "&down'><button type='button'>Click For TimeSheet</button></a>";
            // echo "Mailer Error: {$mail->ErrorInfo}</h3></center>";
        }
    } else {
        $pdf->Output($name_file, 'I');
    }
}
